kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: enter-storage-class-name-here
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: 'true'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:addonmanager.kubernetes.io/mode': {}
            'f:kubernetes.io/cluster-service': {}
        'f:parameters':
          .: {}
          'f:billingType': {}
          'f:classVersion': {}
          'f:iopsPerGB': {}
          'f:sizeRange': {}
          'f:type': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: ibm.io/ibmc-file
parameters:
  billingType: hourly
  classVersion: '2'
  iopsPerGB: '2'
  sizeRange: '[20-12000]Gi'
  type: Endurance
reclaimPolicy: Delete
volumeBindingMode: Immediate
